### ISSUE TITLE
Server is not syncing to other ones

### ISSUE THREAD

**Issue by T-X** [mozilla/gpg.mozilla.org#3]
Hi,

A year ago I had the same problem and now when doing my annual expiration update I ran into the same issue again:

On the 1st of February 2019 I updated the expiration time and uploaded the new signature to gpg.mozilla.org:

https://gpg.mozilla.org/pks/lookup?op=vindex&fingerprint=on&search=0xBC723E2000B7A52F

However, the update does not seem to propagate. For instance keys.gnupg.net does not have it a month later:

http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0xBC723E2000B7A52F

Last year I worked around this issue by switching the GPG server via gnupg.conf and reuploading it manually to other servers.

**Comment by gene1wood** [comment]
I also observed this with a key (where it was uploaded to gpg.mozilla.org and unavailable many months later on keyserver.ubuntu.com) and assumed it was due to a problem on the Canonical ubuntu side.

I contacted them

> I noticed that a key on our GPG server wasn't present on Ubuntu's. I went and looked and it appears that Canonical's gossip peers are currently restricted to only Canonical hosts
> 
> http://keyserver.ubuntu.com:11371/pks/lookup?op=stats
> 
> boquila.canonical.com 11370
> cassava.canonical.com 11370
> 10.15.38.7 11370
> 
> 1. Is this an operational issue on Canonical's side and there should be additional non-Canonical gossip peers linked to keyserver.ubuntu.com?
> 2. If not, does Canonical have any interest in peering with Mozilla in order to integrate with the larger mesh of keyservers?

And heard back

>  We actually do gossip via a private server to keep oversize keys out of our keyserver mesh, so that peer list is incomplete, we're in the global mesh.

So I think the problem is on our (Mozilla)'s side

cc @gdestuynder

**Comment by gdestuynder** [comment]
@gene1wood , as I mentioned IRL when you mentioned the Ubuntu keyserver, the gpg.mozilla.org keyserver does not sync with the Ubuntu keyserver at this time.
You can find the number of updates and peers at https://gpg.mozilla.org/pks/lookup?op=stats

This is due to the way key server synchronization works: there is no single master, so key sets become disjointed when there is no commonality in the list of SKS keyservers being synced, which is the case right now.


https://wiki.gnupg.org/WKD is also a good way to distribute keys that is currently more reliable as it does not rely on this

see also https://jira.mozilla.com/browse/EIS-602

**Comment by gene1wood** [comment]
> as I mentioned IRL when you mentioned the Ubuntu keyserver, the gpg.mozilla.org keyserver does not sync with the Ubuntu keyserver at this time.

No no sorry I meant that I was expecting the key to end up on Ubuntu's server, not directly from gpg.mozilla.org but through a chain of sks servers passing updates along.

> so key sets become disjointed when there is no commonality in the list of SKS keyservers being synced

Totally, makes sense

> which is the case right now.

Ah sorry I didn't know that. How does one view if there's commonality between sks servers? How can I tell what servers are linked by other servers to gpg.mozilla.org?

**Comment by T-X** [comment]
Thanks for the replies and explanations so far! Just wanted to ask, is it in any way useful (for debugging?) if I wait with the reuploading of my key to another server a little longer?

Or can I just switch to another key server?

**Comment by gdestuynder** [comment]
> Ah sorry I didn't know that. How does one view if there's commonality between sks servers? How can I tell what servers are linked by other servers to gpg.mozilla.org?

There may be better ways but looking up the `pks/lookup?op=stats` of each server allows to see which servers are syncing. If server A syncs to server B and server B syncs to server C you're good. If not, no key.
This means looking up the stats of each sync'd server.

Some can also be part of a pool (f.e. https://sks-keyservers.net/overview-of-pools.php)


@T-X you can just do `gpg --keyserver xxx --send-key yyyy` for example if you want to make sure it end up on a specific keyserver

**Comment by lhirlimann** [comment]
> Some can also be part of a pool (f.e. https://sks-keyservers.net/overview-of-pools.php)

Is the Mozilla gpg server part of a pool?

**Comment by gene1wood** [comment]
We've opted to take down the gpg.mozilla.org SKS service so we won't be modifying the peers.

**Comment by T-X** [comment]
Okay, thanks for the update. And thanks to everyone who had been working on and maintaining this so far!
